### ISSUE TITLE
methods to realize a reflexive pronoun

### ISSUE THREAD

**Issue by fmorbini** [simplenlg/simplenlg#23]
Hi, i coded the simplenlg code to construct this sentence:
"The little triangle shakes to defend himself."

depending on the code i use for the last word "himself" i get different results. I cannot explain why.

1) if i use:
NLGElement x = nlgFactory.createWord("him",LexicalCategory.PRONOUN);
x.setFeature(LexicalFeature.REFLEXIVE, true);
then i get the correct "himself".

2) if i use:
NPPhraseSpec ret = nlgFactory.createNounPhrase("him");
ret.setFeature(Feature.PRONOMINAL, true);
ret.setFeature(LexicalFeature.REFLEXIVE, true);

then i get the incorrect "him".

i also tried to use:
3) NPPhraseSpec ret = nlgFactory.createNounPhrase(x); where x is the same object as in case 1 above. Also this doesn't work (i.e. i get "him" instead of "himself")

to me both are correct and i would prefer to use 2. Can you please explain why 2 doesn't work?

thanks

**Comment by scottyli** [comment]
For #2, I think you it's because you are using ```.setFeature()``` on the ```NPPhraseSpec``` and not ```WordElement```

This must not trickle down. Here's what it looks like when you print all the features of ```NPPhraseSpec```

```
TYPE: <type 'simplenlg.phrasespec.NPPhraseSpec'>
CATEGORY: NOUN_PHRASE
WORD_ELEMENT: 
    TYPE: <type 'simplenlg.framework.WordElement'>
    CATEGORY: PRONOUN
    number: SINGULAR
    reflexive: False
    gender: MASCULINE
    person: THIRD
    possessive: False
number: SINGULAR
reflexive: True
expletive_subject: True
gender: MASCULINE
acronym: False
person: THIRD
possessive: False
raised: False
pronominal: True
elided: False
adjective_ordering: True
```
